### ISSUE TITLE
Connected thread '<main>' panicked at 'assertion failed - vault.rs

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/safe_vault#255] opened 2015-09-21 14:16 UTC
Droplet test network - using `routing 0.3.12` and `crust 0.2.12`

Intermittent error that seems only to be randomly reproducable? 

```
INFO:safe_vault::vault: Vault fc0c35..a5c1c5 received an event from routing : Connected
thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `8`, right: `7`)', src/vault.rs:177
```

**Comment by maqi** [comment] 2015-09-21 14:25
The issue is due to connected event is being fired before churn event sometime.
anyway, the assert is a quite old code inherited from TODOs, so can be removed.

resolved in the PR https://github.com/maidsafe/safe_vault/pull/256

**Closed by maqi** 2015-09-21 14:25 UTC
